spring.application.name=QuanLyQuanCafe
spring.datasource.url=jdbc:mysql://localhost:3306/quanlyquancafe
spring.datasource.username=root
spring.datasource.password=



spring.jpa.hibernate.ddl-auto=update

gemini.api.key=AIzaSyABTzva78pw8kS_He-kPp1j-jYwT45ms5c
gemini.model=gemini-2.5-flash